id = "pigs-in-space"
name = "Pigs in Space"
version = "0.1.0"
schema_version = 1
authors = ["kreek"]
description = "A dark color theme designed to be easy on the eyes. Inspired by Solarized with a pastel twist."
repository = "https://github.com/kreek/pigs-in-space-zed"
